version: "3"

services:
  # cache: 
  #   hostname: cache_app
  #   container_name: "cache_app"
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - app

  ecotec:
    container_name: "api-ecotec"
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - '.env'
    # command: 'npm install'
    volumes:
        - "./:/usr/src/app"
    ports:
      - 8080:8080
    # links:
    #   - "cache"
    # depends_on:
    #   - cache
    networks:
      - app
      
networks:
  app:
    driver: bridge